### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by anguscb** [maya142857/ftx-line-notify#1]
Traceback (most recent call last):
  File "/home/angus/own/ftx/arbitrage.py", line 88, in <module>
    cost_24h = cost_24h + borrow_history[i]['cost']
IndexError: list index out of range

======================================
coinlist = ['FIDA','FIDA-PERP'] #套利幣種

**Comment by maya142857** [comment]
應該是因為我偷懶，直接往前抓24筆資料，如果借錢的利息紀錄不足24筆會跳錯，晚點修

**Comment by maya142857** [comment]
coinlist = ['FIDA-PERP'] is fine
