### ISSUE TITLE
Error   

### ISSUE THREAD

**Issue by joneyemine** [maya142857/ftx-line-notify#2]
IndexError                                Traceback (most recent call last)
<ipython-input-26-aa4ff8d5c59a> in <module>()
     85     borrow_history = subaccount.get_borrow_history()
     86     for i in range(24):
---> 87         cost_24h = cost_24h + borrow_history[i]['cost']
     88 
     89     payment_24h = 0

IndexError: list index out of range

**Comment by joneyemine** [comment]
coinlist = ['BADGER-PERP']    這部分沒問題

**Comment by maya142857** [comment]
如果沒有借錢套利，USD值不是負數的話，直接把85-87行註解掉即可。

**Comment by joneyemine** [comment]
感謝你   已經用好了
